### ISSUE TITLE
old ontology pickle files in the KG2 build instance do not get updated

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#101]

**Comment by saramsey** [comment]
On `kg2steve.rtx.ai`:

![Screen Shot 2021-08-04 at 2 49 33 PM](https://user-images.githubusercontent.com/5562107/128259740-855540e7-a298-4b78-8e0f-3d06fc1015a7.png)

**Comment by saramsey** [comment]
@acevedol is this causing an issue in practice?  Are pickled versions of the ontologies now being generated in `/home/ubuntu/kg2-build` during the current KG2pre build process, and if so, are they deleted before a new build is started?

**Comment by acevedol** [comment]
@saramsey No, I'm not generating pickled versions of ontologies at all. I am typically generating .ttl or .owl files and converting them to json.

**Comment by saramsey** [comment]
Thank you, given the changes in documentation [here](https://github.com/RTXteam/RTX-KG2/commit/071a6978b6ee7e812f26033291cc56800f31e9c7), can we close this issue then?

**Comment by ecwood** [comment]
Yes, that's fine with me.
