### ISSUE TITLE
uncaught psql error in extract-drugcentral.sh

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#108]
Seeing this error message in `extract-drugcentral.log`:
```
+ sudo -u postgres psql -c 'DROP DATABASE IF EXISTS drugcentral'
NOTICE:  database "drugcentral" does not exist, skipping
DROP DATABASE
+ sudo -u postgres psql -c 'CREATE DATABASE drugcentral'
CREATE DATABASE
+ gunzip -c /home/ubuntu/kg2-build/drugcentral/drugcentral.sql.gz
+ sudo -u postgres psql drugcentral
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
SET
SET
CREATE TABLE
ERROR:  role "jjyang" does not exist
```

**Comment by saramsey** [comment]
Second problem, the script `extract-drugcentral.sh` is "finishing" (i.e., not terminating early) even though there are errors in some of the SQL statements:
```
Thu Aug  5 00:17:27 UTC 2021
+ echo '================= finished extract-drugcentral.sh =================='
================= finished extract-drugcentral.sh ==================
```
This is apparently a "known issue" with the way we are piping SQL into `psql`, as documented in this excellent blog posting by Strahinja Kustudic:
https://engineering.nordeus.com/psql-exit-on-first-error/

**Comment by saramsey** [comment]
I've implemented (I think?!) Kustudic's recommended countermeasure in bfe2937

**Comment by saramsey** [comment]
my previous commit didn't fix the issue; current thinking is that the `create role` SQL statement needs to occur before the DB import.

**Comment by saramsey** [comment]
Hi @acevedol can we close this issue?  Is it fixed?

**Comment by acevedol** [comment]
Yes, this was fixed
