### ISSUE TITLE
push `kg2-simplified.json.gz` to NCATS repo

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#130]
kg2-simplified.json.gz is about 8GB, which is too large to push to Github

**Comment by acevedol** [comment]
Compressed kg2-simplified.json.gz with xz, bringing the file size down to about 4.8 GiB

**Comment by saramsey** [comment]
Hi @acevedol for your `xz` compressed file, what is the actual file size in bytes?

**Comment by saramsey** [comment]
Hi @acevedol:  just an FYI, I tried using `lzip -9` to compress `kg2-simplified.json`, but the compressed file size (5255987200 bytes) is not as small as what `xz -9` achieved (4923993220 bytes). So I think we should stick with `xz`.
