### ISSUE TITLE
Start naming KG2 TSV tarball with version number (in S3)?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#140]
Instead of extracting KG2pre data via Neo4j, going forward the KG2c build process is going to ingest `kg2-tsv-for-neo4j.tar.gz` (downloaded from the `rtx-kg2` S3 bucket).

Wondering if it would be reasonable to start naming that tarball in S3 with the KG2 version number? So, something like:
`kg2-7-2-tsv-for-neo4j.tar.gz`

I realize that means we'd have to periodically delete old versions of the file so the S3 bucket doesn't get overly full, but it'd be really nice for the KG2c build process to be able to make sure it gets the right tarball (since currently the tarball is overwritten every time a new KG2pre build is done).

**Comment by saramsey** [comment]
I have created [branch issue-140](https://github.com/RTXteam/RTX-KG2/tree/issue-140) for working this issue

**Comment by saramsey** [comment]
I have a mini build-system for the `issue-140` branch working on my MBP, for development/test purposes for this issue.

**Comment by saramsey** [comment]
Wondering if we can prioritize this for the next few weeks?  @acevedol and @ecwood do you think it is doable?

**Comment by saramsey** [comment]
I'm specifically thinking that the *output* filenames that go to the S3 bucket should have the version number in the filename. I don't think the filenames on `buildkg2.rtx.ai` or whatever need 
to have the version number in the filename.

**Comment by ecwood** [comment]
I can try to work on this in the next few weeks. I like the idea of a version-named folder on S3 to avoid clutter.

**Comment by amykglen** [comment]
is there any way this could be implemented soon? really all we would like is that the `kg2-tsv-for-neo4j.tar.gz` in S3 is somehow named with its version number - either in the filename itself or by putting it in a subdirectory for that version. no need to change the file name within the KG2pre build itself (just upon upload to S3). it would be a big help for improving the robustness of KG2c builds.

**Comment by ecwood** [comment]
This should be done now. It will look something like `kg2-tsv-for-neo4j-KG2.X.Y.tar.gz` in the next build.

**Comment by amykglen** [comment]
awesome, thank you!!

**Comment by ecwood** [comment]
This was successful in the KG2.10.1pre build, other than the report compare (as described here: https://github.com/RTXteam/RTX-KG2/issues/408#issuecomment-2336826509), so I am closing out this issue.

**Comment by saramsey** [comment]
Thank you @ecwood for doing this!
