### ISSUE TITLE
test out upload of KG2.7.3c to the Translator Knowledge Graph Exchange (KGE)

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#153]
Contact person for KGE questions is Richard Bruskiewich (SRI Team).

**Comment by saramsey** [comment]
Richard suggests that we test uploading KG2.7.3c to their test KGE instance. The URL for that KGE instance is: https://kge-data-staging.starinformatics.ca/

**Comment by RichardBruskiewich** [comment]
Hi all, @saramsey if anyone else on your team needs an account to assist with the uploading, let me know. Alternately,  you can give them your credentials for the upload. Lest this sound secure, this will put your name on the upload and besides, I'm going to  be resetting the user account database soon for the Translator production server, so you'll get a new account there anyhow.

**Comment by saramsey** [comment]
see https://github.com/RTXteam/RTX/blob/master/code/kg2c/kg2c_tsv_to_kgx_tsv.py

**Comment by saramsey** [comment]
Done (marked as fileset `KG2c` and version "7.3")
<img width="480" alt="Screen Shot 2021-09-24 at 7 45 24 PM" src="https://user-images.githubusercontent.com/5562107/134755345-17567573-d00c-43de-9fde-73718643ca78.png">

**Comment by saramsey** [comment]
Now  we need to do KG2. Will do this next week at the relay.

**Comment by saramsey** [comment]
OK, @acevedol is working on the KGX export of KG2, as a first step toward uploading KG2 to KGE.

**Comment by saramsey** [comment]
Upload of KG2.7.3c to KGE was successful.
