### ISSUE TITLE
upgrade KG2 to biolink 2.2.6

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#165]
Due: Nov. 1

**Comment by acevedol** [comment]
On branch `issue165`, updated `curies-to-urls-map.yaml`
bidirectional mapping: 
- MESH: http://id.nlm.nih.gov/mesh/
- miRBase: http://identifiers.org/mirbase
- SNOMED: http://www.snomedbrowser.com/Codes/Details/
- STY: http://purl.bioontology.org/ontology/STY/

contraction only:
- MESH: http://purl.bioontology.org/ontology/MESH/
- miRBase: "https://identifiers.org/mirbase:"
- SNOMED: http://purl.bioontology.org/ontology/SNOMEDCT/

**Comment by saramsey** [comment]
changed to Biolink 2.2.6 per request from Chris Bizon
