### ISSUE TITLE
Can we support Biolink 2.2.7?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX-KG2#171]
Chris Bizon just let me know that they just released Biolink 2.2.7 and it includes a fix to predicates that were going the wrong way compared to their peers, including one that seemed relevant to a December Demo query. I forget which one that was.

Chris asked if ARAX (/RTX-KG2) can update to Biolink 2.2.7 to fix this directionality problem?

I said I'd check. Is this feasible?

**Comment by saramsey** [comment]
@acevedol and I have confirmed that Biolink 2.2.6 has the inverse predicate changes that cbizon wanted for Workflow A. We are aiming to build KG2.7.4 against Biolink 2.2.6.

**Comment by saramsey** [comment]
See issue #166
