### ISSUE TITLE
Assertion Error in 2.7.4 build

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#177]
Build crashed again on Ontologies and TTl rule with an Assertion Error
```
[http://purl.bioontology.org/ontology/HGNC/] subject node ontology ID has no curie ID in the map: http://purl.bioontology.org/ontology/HGNC/HGNC%3A3144
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1362, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 190, in make_kg2
    map_of_node_ontology_ids_to_curie_ids)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1047, in get_rels_dict
    assert False, "Cannot map predicate name: " + edge_pred_string + " to a predicate CURIE, in ontology: " + ontology.id
AssertionError: Cannot map predicate name: type to a predicate CURIE, in ontology: http://purl.obolibrary.org/obo/go/extensions/go-plus.owl
```

_Originally posted by @acevedol in https://github.com/RTXteam/RTX-KG2/issues/166#issuecomment-961228186_

**Comment by acevedol** [comment]
The assertion error comes from multi_ont_to_json_kg.py
https://github.com/RTXteam/RTX-KG2/blob/720e562a4130111aba2d8f716bc7abf25c844351/multi_ont_to_json_kg.py#L1047

**Comment by acevedol** [comment]
The URI for Gene Ontology is in ont-load-inventory.yaml https://github.com/RTXteam/RTX-KG2/blob/ff0d2dba4c695fdce085b747f2d8a9479065f663/ont-load-inventory.yaml#L186

**Comment by saramsey** [comment]
@acevedol what commit fixed this issue, in the end?  is it fixed?  I assume it is, since the build completed. Would be good to touch base about what the eventual fix was.

**Comment by acevedol** [comment]
@saramsey I didn't have this issue on the 2.7.5 test build, but I don't remember what exactly fixed it at the time.
