### ISSUE TITLE
URL shortener needs a tweak to handle BSPO predicates

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#178]
This error message in `filter_kg_and_remap_predicates.py` (reported by @acevedol in issue #166) likely indicates that we need to tweak `curies-to-urls-map.yaml`:
```
original predicate curie is missing from the YAML config file: OBO:bspo#parallel_to
```

**Comment by saramsey** [comment]
has this issue been fixed?  if so, which commit fixed it?

**Comment by saramsey** [comment]
HI @acevedol just checking back on this?

**Comment by acevedol** [comment]
It was fixed in commit `https://github.com/RTXteam/RTX-KG2/commit/8f547585b6a9cd13082e0ade2cb59a9baccb71da`
