### ISSUE TITLE
Wrong category for UMLS:C3542922 in KG2.5.2?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#19]
in KG2.5.2, this UMLS node seems like it should be a protein or something of that sort (based on its name), but it's labeled as a disease:

```
match (n {id:"UMLS:C3542922"}) return n.id, n.name, n.category
```

n.id | n.name | n.category
-- | -- | --
"UMLS:C3542922" | "Complement component receptor 2" | "biolink:Disease"

noticed because it's being coalesced with protein/gene nodes in KG2c. thanks to @edeutsch's new `expanded_categories`, I think it won't be returned in ARAX queries asking for diseases, but thought I should report it to the KG2 team nonetheless.

**Comment by ericawood** [comment]
This appears fixed in `KG2.6.7`:
![image](https://user-images.githubusercontent.com/36611732/123871226-4feee280-d8e8-11eb-9d8a-7ac2e3b616a9.png)
