### ISSUE TITLE
KGX export of KG2.7.4c and upload to KGE

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#190]
One of the last steps for the KG2.7.4 build is that we need to make a KGX export of KG2.7.4c using this script

https://github.com/RTXteam/RTX/blob/master/code/kg2c/kgx-validation-and-metagraph.sh

and upload the resulting archive to KGE.

**Comment by saramsey** [comment]
This is the script that does the export: https://github.com/RTXteam/RTX/blob/master/code/kg2c/kg2c_tsv_to_kgx_tsv.py

**Comment by acevedol** [comment]
Ran `kg2c_tsv_to_kgx_tsv.py` to generate nodes.tsv and edges.tsv
