### ISSUE TITLE
KG2.7.5 build

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#193]
- [x] make sure Travis CI test-suite passes
- [x] run a "all -F" build with the "-n" flag
- [x] check the output of the "-n" run to make sure every target will be run
- [x] run a "all -F" build without the "-n" flag (this should take approximately 48 hours)
- [x] verify that the new build is in fact versioned 2.7.5
- [x] check report file `kg2-simplified-report.json`; compare against previous `kg2-simplified-report.json` to identify any major changes
- [x] install the new KG2 TSV files into Neo4j on `kg2endpoint4.rtx.ai`
- [x] create a DNS CNAME record for `kg2-7-5.rtx.ai` pointing to `kg2endpoint4.rtx.ai`
- [x] document the build in `kg2-versions.md` in the `master` branch
- [x] tag the RTX-KG2 master branch and do a GitHub "release" with version `KG2.7.5`
- [x] build Node Synonymizer against KG2.7.5-neo4j
- [x] build `KG2.7.5c`
- [x] validate `KG2.7.5c`
- [x] push `kg2c_lite_2.7.5.json.gz` to [NCATS repo](https://github.com/ncats/translator-lfs-artifacts/tree/main/files)
- [ ] coordinate with Amy
- [ ] coordinate with Eric, Finn, and Chunyu for handoff

**Comment by acevedol** [comment]
Assertion error in validation scripts. Getting caught on relation_label: gene_associated_with_condition

**Comment by acevedol** [comment]
Error in validate_kg2_util_curies_urls_categories.py

```
Reading ontology JSON file: /home/ubuntu/kg2-build/biolink-model.owl.json; size: 575.26 KiB
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_kg2_util_curies_urls_categories.py", line 73, in <module>
    assert kg2_util.CURIE_PREFIX_BIOLINK + ':' + relation_label in biolink_edge_labels, relation_label
AssertionError: gene_product_of
```

**Comment by saramsey** [comment]
Here's the reprex for the issue posted for `gene_product_of`:

1. `ssh ubuntu@buildkg2.rtx.ai`
2. `cd /home/ubuntu/kg2-build`
3. export PATH=$PATH:/home/ubuntu/kg2-build
4. `~/kg2-venv/bin/python3 -u ~/kg2-code/validate_kg2_util_curies_urls_categories.py  ~/kg2-code/curies-to-urls-map.yaml  https://raw.githubusercontent.com/biolink/biolink-model/2.2.11/biolink-model.owl.ttl /home/ubuntu/kg2-build/biolink-model.owl.ttl`

**Comment by saramsey** [comment]
Here's the reprex for the same issue, on my MBP:
1. `cd ~/Work/Proj/kg2/RTX-KG2`
2. `venv/bin/python3 -u validate_kg2_util_curies_urls_categories.py  curies-to-urls-map.yaml https://raw.githubusercontent.com/biolink/biolink-model/2.2.11/biolink-model.owl.ttl ./biolink-model.owl.ttl`

produces:
```
Reading ontology JSON file: ./biolink-model.owl.json; size: 576.57 KiB
Traceback (most recent call last):
  File "/Users/sramsey/Documents/Work/Proj/kg2/RTX-KG2/validate_kg2_util_curies_urls_categories.py", line 73, in <module>
    assert kg2_util.CURIE_PREFIX_BIOLINK + ':' + relation_label in biolink_edge_labels
AssertionError
```

**Comment by saramsey** [comment]
Commit ab16d39 should fix the issue with `validate_kg2_util_curies_urls_categories.py`

**Comment by acevedol** [comment]
Error in Rule Ontologies
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1364, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 143, in make_kg2
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 67, in load_ont_file_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_pickle=save_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 793, in make_ontology_from_local_file
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['owltools', 'genepio.owl', '-o', '-f', 'json', '/tmp/kg2-_z2504xt.json']' returned non-zero exit status 1.
```

**Comment by acevedol** [comment]
Error on rule Finish
```
AttributeError in line 13 of /home/ubuntu/kg2-code/Snakefile:
'InputFiles' object has no attribute 'simplified_output_nodes_file_full'
  File "/home/ubuntu/kg2-code/Snakefile", line 13, in __rule_Finish
  File "/usr/lib/python3.7/string.py", line 186, in format
  File "/usr/lib/python3.7/string.py", line 190, in vformat
  File "/usr/lib/python3.7/string.py", line 230, in _vformat
  File "/usr/lib/python3.7/string.py", line 301, in get_field
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in runESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
```
