### ISSUE TITLE
KGE seems to be semi-deprecated

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#247]
Richard B. has reported via Slack DM that the SRI Team may no longer be able to maintain KGE. So, going forward, for our method for "hosting" KGX serializations of RTX-KG2pre and RTX-KG2c, I guess maybe we will just use the [git-lfs](https://github.com/ncats/translator-lfs-artifacts/tree/main/files) area?  Does that seem feasible and reasonable under the circumstances?  Do we have a workable approach to deal with the filesize limit with git-lfs?  If we are in agreement, should we update the Issue Templates for the KG2pre and KG2c builds?

**Comment by acevedol** [comment]
Git LFS is fine with me. I am dealing with the file size limit by splitting the edges file into 2 or 3 before compressing, which seems to be okay.
