### ISSUE TITLE
KEGG node missing name in KG2.8.0

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#251]
I noticed that this KEGG node doesn't seem to have a `name` in KG2.8.0pre, though I believe it did in prior KG2 versions.
```
match (n {id:"KEGG.COMPOUND:C02700"}) return n
```
```
{
  "iri": "https://identifiers.org/kegg.compound:C02700",
  "knowledge_source": "infores:kegg",
  "category_label": "small_molecule",
  "deprecated": "False",
  "id": "KEGG.COMPOUND:C02700",
  "category": "biolink:SmallMolecule",
  "update_date": "2022-10-07 15:12:06"
}
```

Just wanted to check if this is expected or not. Thanks!

**Comment by acevedol** [comment]
Thanks, Amy. Not expected! It looks like all of the KEGG compounds are missing their names. It might be an issue with the KEGG extraction.

**Comment by acevedol** [comment]
It looks like I have this fixed in the build instance and the corrected version will be in the next build. There was a problem with the name conversion that has been addressed.

**Comment by acevedol** [comment]
![KEGG ID](https://github.com/RTXteam/RTX-KG2/assets/59181061/b794ff7b-24e1-4417-9d59-dfd5b34f7cf3)
