### ISSUE TITLE
Check if we have any SemMedDB edges without PubMed cross-references

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#258]
Per a decision made by the Translator consortium during the Winter 2023 relay (and as communicated in [RTX issue 1965](https://github.com/RTXteam/RTX/issues/1965)), if a KP returns a SemMedDB-derived edge, that edge should be annotated with at least one PubMed cross reference. We should check to make sure that this is the case for RTX-KG2.

**Comment by acevedol** [comment]
Yes, I don't think there are any SemMedDB edges without PMIDs. 
![Screen Shot 2023-03-29 at 3 41 58 PM](https://user-images.githubusercontent.com/59181061/228684196-35709d32-b6d2-459f-b94c-4cd092bf972e.png)

**Comment by edeutsch** [comment]
Get rid of all those and you will surely reduce the number of false positives! 😁

Yet, I'm thinking some may be wrong here. Andrew Su looked into this and advocated this threshold, and I am skeptical that he would advocate removing 95% of the edges, so I think something is amiss here. I don't think Andrew ever said how many that gets rid of. Maybe we should ask him: how many edges does he think are deleted with his 10-PMID rule?

**Comment by saramsey** [comment]
@acevedol: Thank you for this analysis.

Just to add a bit of context, if I may. @edeutsch is absolutely right. But based on conversations and the discussion at the AHM, I think we are leaning towards providing filtering capability in the RTX-KG2 KP, not in the KG2pre build process. Please see the ARAX parent issue https://github.com/RTXteam/RTX/issues/1972 for ongoing discussion and specific thoughts about remediation via changes to the RTX-KG2 KP.
