### ISSUE TITLE
switch to "primary_knowledge_source" and no more edge-merging

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#263]
This issue is motivated by [RTX issue 1970](https://github.com/RTXteam/RTX/issues/1970). 

See this line of the Biolink model YAML file, which shows that `primary_knowledge_source` has `multivalued: false`. See also the T[ranslator architecture document ](https://github.com/NCATSTranslator/TranslatorArchitecture)(Section 10.ii). 

Also need to switch the node property `knowledge_source` to a multivalued property `provided_by`, per the Biolink spec.

**Comment by acevedol** [comment]
@saramsey , @amykglen pointed out during this morning's AHM that we need more granularity in `primary_knowledge_source`. We are supposed to include the source's source, if any, as the primary knowledge source. Noting this here for further discussion (and better description of the problem as we go along).

**Comment by amykglen** [comment]
thanks @acevedol! yeah, the definition of primary_knowledge_source in the biolink model includes an example (for chembl):
```
  primary knowledge source:
    is_a: knowledge source
    description: >-
      The most upstream source of the knowledge expressed in an Association that an
      implementer can identify.  Performing a rigorous analysis of upstream data providers is expected; every effort
      is made to catalog the most upstream source of data in this property.  Only one data source should be declared
      primary in any association.  "aggregator knowledge source" can be used to caputre non-primary sources.
    range: information resource
    notes: >-
      For example: a single ChemicalToGene Edge originally curated by ClinicalTrials.org, is aggregated by ChEMBL, then 
      incorporated into the MolePro KP, then sent via TRAPI message to the ARAGORN ARA, and finally sent to 
      the NCATS ARS. The retrieval path for this Edge is as follows: 
      ARS--retrieved_from-->  ARAGORN  --retrieved_from-->   MolePro  --retrieved_from--> ChEMBL --retrieved_from-->  ClinicalTrials.gov
      The "primary knowledge source" for this edge is "infores:clinical-trials-gov". 
     "infores:chembl" and "infores:molecular_data_provider" are listed in the "aggregator knowledge source" property.
    multivalued: false
```
note that at today's AHM Jared suggested that if it's not obvious what a source's primary source is, we probably shouldn't spend time trying to figure it out, and instead just record that source itself as the 'primary_knowledge_source'.

**Comment by saramsey** [comment]
OK, I believe that @acevedol and @sundareswarpullela and @amykglen have this under control, so I'm taking myself off the assignment list for this issue.

**Comment by saramsey** [comment]
> note that at today's AHM Jared suggested that if it's not obvious what a source's primary source is, we probably shouldn't spend time trying to figure it out, and instead just record that source itself as the 'primary_knowledge_source'.

100% agree
