### ISSUE TITLE
apparent bug in kg_json_to_tsv.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#273]
In `kg_json_to_tsv.py`, this line of code doesn't seem right:
https://github.com/RTXteam/RTX-KG2/blob/1514437f5b81f1b457458a16d1775e8d081222a5/kg_json_to_tsv.py#L297

The construction `not "None"`, i.e., the predicate for the `if` statement, always evaluates to `False`. I think maybe what was intended was:

```
value = (edge['qualified_predicate'] if edge['qualified_predicate'] is not "None" else edge['source_predicate'])
```

**Comment by acevedol** [comment]
Line no longer used as of 153748b
