### ISSUE TITLE
kg_json_to_tsv.py seems to be putting out a TSV file with DOS line termination

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#278]
I suspect this is an issue with the "tsv" PyPI packge. It should put out a file with Linux line termination.

**Comment by saramsey** [comment]
Classifying this as a `bug`. DOS line termination is inappropriate in a text file serialized and consumed on a Linux system.

**Comment by ecwood** [comment]
As of the `KG2.8.5pre` TSV's, this is no longer an issue. I am closing this issue.

**Comment by saramsey** [comment]
Thanks for fixing this, @ecwood. 

Incidentally, I finally discovered why the Python csv module has the (to me) odd default behavior of encoding end-of-line as CRLF even on Linux systems; the answer is [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180). Fortunately, we are not aiming to produce an RFC 4180-compliant "CSV" file (with a "text/csv" MIME type) but rather, a valid text file for Linux systems that happens to use tab as a record delimiter. :-)
