### ISSUE TITLE
Unsightly descriptions for Uniprot protein nodes in KG2 graph

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX-KG2#279]
We still have the issue that some protein descriptions are very large and unsightly, which is being flagged at the UI level. I think this is KG2 ingest issue. Should the KG2 ingest be updated to make these more sightly?

Long discussion of issue here:
https://github.com/NCATSTranslator/Feedback/issues/112

Unclear what to do.

Alternatively, the KG2 service could detect such unsightly descriptions and just extract the FUNCTION part, for example

**Comment by saramsey** [comment]
Thank you for putting this issue in RTX-KG2. Working on it now.

**Comment by saramsey** [comment]
This is for Uniprot nodes only

**Comment by saramsey** [comment]
This is an issue in `uniprotkb_dat_to_json.py`. I'm fixing it and doing some other fixes, including:

- including only the `FUNCTION` and `SIMILARITY` subsections of the description (and removing all other subsections and removing the allcaps subsection names and Uniprot-DAT-file-format's quirky hyphen-exclamation-hyphen subsection separators)
- detecting OMIM cross-references in the `DISEASE` subsection and converting those into `biolink:causes` edges (these show up in the Uniprot DAT file in the description `DISEASE` subsection as CURIEs with `MIM:` as the prefix)
- removing parenthesis-delimited and brace-delimited cross-references (i.e., all those ECO and PMID curies) from the description

**Comment by saramsey** [comment]
slated for inclusion in the KG2.8.4pre build

**Comment by saramsey** [comment]
OK, I ran this Cypher code
```
match (n {id: 'UniProtKB:P34998'}) return n.description
```
on the `kg2-8-3c.rtx.ai` endpoint, and got: 
> "-!- FUNCTION: G-protein coupled receptor for CRH (corticotropin-releasing factor) and UCN (urocortin). Has high affinity for CRH and UCN. Ligand binding causes a conformation change that triggers signaling via guanine nucleotide-binding proteins (G proteins) and down-stream effectors, such as adenylate cyclase. Promotes the activation of adenylate cyclase, leading to increased intracellular cAMP levels. Inhibits the activity of the calcium channel CACNA1H. Required for normal embryonic development of the adrenal gland and for normal hormonal responses to stress. Plays a role in the response to anxiogenic stimuli. {ECO:0000269|PubMed:18292205, ECO:0000269|PubMed:18801728, ECO:0000269|PubMed:23576434, ECO:0000269|PubMed:23863939}. -!- SUBUNIT: Heterodimer; heterodimerizes with GPER1 (By similarity). Interacts (via N-terminal extracellular domain) with CRH and UCN. Interacts with DLG1; this inhibits endocytosis of CRHR1 after agonist binding. {ECO:0000250, ECO:0000269|PubMed:18801728, ECO:0000269|PubMed:20843795, ECO:0000269|PubMed:20966082, ECO:0000269|PubMed:23576434, ECO:0000269|PubMed:23863939}. -!- INTERACTION: P34998; P06850: CRH; NbExp=5; IntAct=EBI-3870393, EBI-3870390; P34998; Q12959: DLG1; NbExp=2; IntAct=EBI-3870393, EBI-357481; P34998; Q14160: SCRIB; NbExp=3; IntAct=EBI-3870393, EBI-357345; P34998; Q63622: Dlg2; Xeno; NbExp=2; IntAct=EBI-3870393, EBI-396947; P34998; O88382: Magi2; Xeno; NbExp=2; IntAct=EBI-3870393, EBI-696179; -!- SUBCELLULAR LOCATION: Cell membrane; Multi-pass membrane protein. Endosome. Note=Agonist-binding promotes endocytosis. -!- ALTERNATIVE PRODUCTS: Event=Alternative splicing; Named isoforms=5; Name=CRF-R1; IsoId=P34998-1; Sequence=Displayed; Name=CRF-R2; IsoId=P34998-2; Sequence=VSP_001997; Name=CRF-R3; IsoId=P34998-3; Sequence=VSP_001996, VSP_001997; Name=CRF-R4; Synonyms=1D; IsoId=P34998-4; Sequence=VSP_001997, VSP_001998; Name=5; IsoId=P34998-5; Sequence=VSP_045434; -!- TISSUE SPECIFICITY: Predominantly expressed in the cerebellum, pituitary, cerebral cortex and olfactory lobe. {ECO:0000269|PubMed:8243652}. -!- DOMAIN: The transmembrane domain is composed of seven transmembrane helices that are arranged in V-shape. Transmembrane helix 7 assumes a sharply kinked structure. The antagonist CP-376395 binds at an allosteric site, far from the presumed binding site for the physiological peptide ligand. -!- PTM: C-terminal Ser or Thr residues may be phosphorylated. {ECO:0000269|PubMed:14657255}. -!- PTM: Phosphorylation at Ser-330 by PKA prevents maximal coupling to Gq-protein, and thereby negatively regulates downstream signaling. {ECO:0000269|PubMed:14657255}. -!- MISCELLANEOUS: [Isoform CRF-R2]: Major isoform. {ECO:0000305}. -!- MISCELLANEOUS: [Isoform CRF-R3]: Does not bind to CRF with high affinity. {ECO:0000305}. -!- SIMILARITY: Belongs to the G-protein coupled receptor 2 family. {ECO:0000305}. ; Short=CRF-R-1; Short=CRF-R1; Short=CRFR-1; Short=CRH-R-1; Short=CRH-R1Evidence Codes from Name:"

the same Cypher query on the `kg2-8-4c.rtx.ai` Neo4j endpoint returns:

> "G-protein coupled receptor for CRH (corticotropin-releasing factor) and UCN (urocortin). Has high affinity for CRH and UCN. Ligand binding causes a conformation change that triggers signaling via guanine nucleotide-binding proteins (G proteins) and down-stream effectors, such as adenylate cyclase. Promotes the activation of adenylate cyclase, leading to increased intracellular cAMP levels. Inhibits the activity of the calcium channel CACNA1H. Required for normal embryonic development of the adrenal gland and for normal hormonal responses to stress. Plays a role in the response to anxiogenic stimuli. Belongs to the G-protein coupled receptor 2 family."
