### ISSUE TITLE
ETL GO-REF references?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#32]
We should look into whether we can bulk ETL the GO_REF entity IDs, like this:

<img width="397" alt="Screen Shot 2020-08-20 at 3 06 57 PM" src="https://user-images.githubusercontent.com/5562107/90830773-25f78780-e2f7-11ea-8960-5c878277a226.png">

**Comment by ecwood** [comment]
This is finished with [`extract-go-annotations.sh`](https://github.com/RTXteam/RTX-KG2/blob/master/extract-go-annotations.sh) and [`go_gpa_to_kg_json.py`](https://github.com/RTXteam/RTX-KG2/blob/master/go_gpa_to_kg_json.py) .
