### ISSUE TITLE
KG2 Validation issue

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX-KG2#345]
The following external issue: https://github.com/NCATSTranslator/Feedback/issues/495
shows:
```
	$ infores:semmeddb -> infores:rtx-kg2 -> infores:arax
		# activity:
		- edge_id | qualifier_type_id: 
			NCBIGene:4763[biolink:Gene|biolink:Protein]--biolink:affects->MESH:D020558[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->MESH:C545445[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->MESH:D015850[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->MESH:D016207[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->MESH:D016328[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->MESH:D053583[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:3351[biolink:Gene|biolink:Protein]--biolink:affects->UMLS:C0036751[biolink:ChemicalEntity] | biolink:object_aspect_qualifier
			NCBIGene:5027[biolink:Gene|biolink:Protein]--biolink:affects->PUBCHEM.COMPOUND:5460341[biolink:ChemicalEntity|biolink:SmallMolecule|biolink:Drug] | biolink:object_aspect_qualifier
```

I think the issue is that "activity" is an invalid object_aspect_qualifier

**Comment by saramsey** [comment]
@edeutsch I'm seeing the following in `biolink-model.yaml`. Seems to me that `activity` is an allowed value for `GeneOrGeneProductOrChemicalEntityAspectEnum`, which (per private communication with Matt Brush) is the definitive list of allowed values for "aspect qualifiers" in Biolink:
https://github.com/biolink/biolink-model/blob/54d9e7ac2023ff97ee634411abdc2a41d359862e/biolink-model.yaml#L10814

**Comment by saramsey** [comment]
@ecwood I am not yet convinced we have a validation issue here. Let's investigate/discuss further before doing any remediation.

**Comment by saramsey** [comment]
tagging @acevedol

**Comment by saramsey** [comment]
tagging @acevedol (testing out notifications, not trying to be a pest)

**Comment by saramsey** [comment]
@edeutsch you are right that the aforementioned triple (the first one) is missing a `object_direction_qualifier`. I concur with @ecwood that this is a known issue already fixed in code and for which the fix should be rolled out in KG2.8.6c.

**Comment by edeutsch** [comment]
After consultation with Richard, I think I understand now. he said:

This validation error is a known issue and arises because Gene--affects->ChemicalEntity does not have a biolink:Association documenting qualifier ranges (in slot_usage)
[4:30](https://ncatstranslator.slack.com/archives/D013XT67KPW/p1693524646936249)
I have noted, however, that an inverse association, ChemicalEntity--affects-->Gene is available
[4:30](https://ncatstranslator.slack.com/archives/D013XT67KPW/p1693524656965169)
and does have the require qualifier definitions
[4:33](https://ncatstranslator.slack.com/archives/D013XT67KPW/p1693524789032019)
That is the same issue as described as part of my comment yesterday
[4:34](https://ncatstranslator.slack.com/archives/D013XT67KPW/p1693524848870829)
(actually, the true inverse association should be ChemicalEntity--affect_by-->Gene

So the way understand it, 'activity" is permitted for Chem affects Gene. But not Gene affects Chem. but this is an acknowledged BL oversight, and will be fixed in BL.

So my understanding is no fix from us is needed here. closing.
