### ISSUE TITLE
UniProtKB shouldn't have KB in the CURIE prefix?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX-KG2#348]
I just noticed that we use the prefix `UniProtKB:`, but it appears it should be `UniProt:`. Eg. Note how this URL doesn't resolve: https://identifiers.org/resolve?query=UniProtKB:Q5STB3, but this one does: https://identifiers.org/resolve?query=UniProt:Q5STB3

Can be reproduced here: https://arax.ncats.io/?term=TNF
![image](https://github.com/RTXteam/RTX-KG2/assets/6362936/8aca8471-1a89-4e7d-966b-cec903f14b45)

**Comment by edeutsch** [comment]
Biolink chose UniProtKB:
https://github.com/biolink/biolink-model/blob/37e245f7755f5878bc1bab12d822b51ae72a88c4/biolink-model.yaml#L143

Pity that Biolink and identifiers.org are out of sync.

but I think we need to go with Biolink.

**Comment by dkoslicki** [comment]
Ah, gotcha. So a nonissue that is kinda an issue; huh!
