### ISSUE TITLE
strange subclass_of edge in KG2.8.1pre

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#357]
From Kaiwen He (reported by Slack DM):

Hi [@ramseyst](https://ncatstranslator.slack.com/team/UUGG2QAF2)
! I notice something weird from an entry in RTX-KG2 2.8.1:
```
MONDO:0008491---rdfs:subClassOf---None---None---None---MONDO:0005015---OBO:mondo.owl	False	MONDO:000501biolink:subclass_of	subclass_of	infores:mondo		{}				subclass_of	rdfs:subClassOf	MONDO:0008491	2023-02-20 21:03:32 GMT	biolink:subclass_of	MONDO:0008491	MONDO:0005015
```
For this edge, it claims that `MONDO:0008491` "stiff-person syndrome" is a subclass of `MONDO:0005015` "diabetes mellitus".
According to the description of stiff-person syndrome, it does not sound like a subtype of diabetes.
Stiff-man syndrome (SMS) is a rare neurological disorder comprising fluctuating trunk and limb stiffness, painful muscle spasms, task-specific phobia, an exaggerated startle response, and ankylosing deformities such as fixed lumbar hyperlordosis.
From this [link](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0008491), there is a tree showing the ontology of  stiff-person syndrome , but diabetes mellitus is not one of the superclasses. [Also attached the screenshot of the tree below]
Could you please verify this edge? I ask because it is related to one of the issues from  NCATSTranslator/Feedback: https://github.com/NCATSTranslator/Feedback/issues/519, given that progressive encephalomyelitis with rigidity and myoclonus is a subclass of  stiff-person syndrome . Thank you for your time!
![Screenshot 2024-01-02 at 11 04 53 AM](https://github.com/RTXteam/RTX-KG2/assets/5562107/80fd0d21-6923-4093-b1a3-45ff86880b01)

https://github.com/NCATSTranslator/Feedback/issues/519

**Comment by saramsey** [comment]
Kaiwen confirms, they saw this edge in KG2.8.1pre (the pre-canonicalized graph).

**Comment by acevedol** [comment]
On KG2.8.6pre I don't see this edge. I ran the query `match (n {id:"MONDO:0008491"})-[r]->(m {id:"MONDO:0005015"}) return *` and returned no results, as shown below. 
![Screenshot 2024-01-08 161422](https://github.com/RTXteam/RTX-KG2/assets/59181061/d82f7b15-90a4-4827-8d42-c7149470fa16)
No results were returned for the same query against 2.8.4pre also
@saramsey Is there another way I should investigate this?

**Comment by saramsey** [comment]
In KG2.10.0c, the only edge between `MONDO:0008491` and `MONDO:0005015` is `biolink:coexists_with`. Closing this issue.

![Screenshot 2024-09-18 at 9 55 39 AM](https://github.com/user-attachments/assets/aff0d4e2-1581-400c-bf56-eb10b3044d24)
