### ISSUE TITLE
Adjust table name `Regulation_2_summation` to `Event_2_summation` for `reactome_mysql_to_kg_json.py` (extension of #297)

### ISSUE THREAD

**Issue by d33bs** [RTXteam/RTX-KG2#362]
Thank you for the fantastic work on RTX-KG2! I wanted to raise an issue I noticed while trying to run the full pipeline. Issue #297 originally highlighted the need to update a table name `Regulation_2_summation` to `Event_2_summation`. While 1503bd62a5c2083a385cb4bd44879213ae067837 did update this in one location for that file, there is another line which still exists with the same issue and seems to cause errors when running the full pipeline.

The following line is where I believe a change is needed: https://github.com/RTXteam/RTX-KG2/blob/master/reactome_mysql_to_kg_jsonl.py#L314

```python
                 LEFT JOIN Regulation_2_summation reg_sum \
```

The following would likely fix this (in alignment with 1503bd62a5c2083a385cb4bd44879213ae067837):

```python
                 LEFT JOIN Event_2_summation reg_sum \
```

Please don't hesitate to let me know if I may further clarify or if you have any questions! Thanks again!

**Comment by acevedol** [comment]
Thank you for pointing this out! The update to the reactome ETL was included in https://github.com/RTXteam/RTX-KG2/commit/ba93acbff9b0a7ae3797e2cbace955d3c1c7bda8
