### ISSUE TITLE
TRAPI 1.5 validation error - result node binding attributes missing

### ISSUE THREAD

**Issue by maximusunc** [RTXteam/RTX-KG2#376]
My understanding is that result node binding attributes are required: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L665

**Comment by saramsey** [comment]
Thank you @kvnthomas98 I suppose this issue should be moved to the RTX project area. What do you think?

**Comment by saramsey** [comment]
@maximusunc we will get this fixed for the Eel release of the RTX-KG2 KP.

**Comment by kvnthomas98** [comment]
@saramsey I agree! I'll raise an issue there.

**Comment by cbizon** [comment]
Strongly agree

**Comment by maximusunc** [comment]
Hey @kvnthomas98 I'm running some queries against dev and seeing the same TRAPI validation error.

**Comment by kvnthomas98** [comment]
@maximusunc can you send me the query you used and also the arax/kg2 endpoint called?

**Comment by maximusunc** [comment]
Sure:
```text
curl -X POST https://arax.ncats.io/beta/api/rtxkg2/v1.4/query \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": {
    "query_graph": {
      "nodes": {
        "disease": {
          "ids": ["MONDO:0004979"],
          "categories": ["biolink:Disease"],
          "set_interpretation": "BATCH",
          "constraints": []
        },
        "e": {
          "categories": ["biolink:ChemicalEntity"],
          "set_interpretation": "BATCH",
          "constraints": []
        }
      },
      "edges": {
        "edge_0": {
          "subject": "e",
          "object": "disease",
          "predicates": ["biolink:treats"],
          "attribute_constraints": [],
          "qualifier_constraints": []
        }
      }
    }
  },
  "bypass_cache": false,
  "submitter": "infores:aragorn"
}' > kg2_response.json
```

One other note is that your urls still reference v1.4 even though you are on v1.5.

**Comment by maximusunc** [comment]
I also just noticed that the result analysis edge bindings all need `attributes` as well.

**Comment by saramsey** [comment]
Regarding the 1.4/1.5 issue, can you please reach out to Eric about that?  He has the latest info, I think.

**Comment by saramsey** [comment]
It's fixed now on `arax.ncats.io/beta/api/rtxkg2/v1.4/query`: 
```
        "node_bindings": {
          "disease": [
            {
              "attributes": [],
              "id": "MONDO:0004979"
            }
```

**Comment by saramsey** [comment]
Seems like edge binding attributes are fixed too?
```
            "edge_bindings": {
              "edge_0": [
                {
                  "attributes": [],
                  "id": "23392974"
                }
              ]
            },
```

**Comment by kvnthomas98** [comment]
Thanks @saramsey and @sundareswarpullela for deploying on the `/beta` and the `/kg2beta` endpoints

**Comment by saramsey** [comment]
Can we close out this issue now?

**Comment by edeutsch** [comment]
yes, thank you all!
