### ISSUE TITLE
Post-move fixes and updates for RTX-KG2 repo

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#54]
- [x] NCATSTranslator/Translator-All wiki page for RTX-KG2
- [x] tag new RTX-KG2 repo with topic "ncats-translator"
- [x] add "about" field for RTX-KG2 repo
- [x] update code link for RTX-KG2 in the [Translator Prototypes Registry](https://d2s.semanticscience.org/docs/translator-prototypes-registry/)
- [x] update all [four files in the KG2 build system code](https://github.com/RTXteam/RTX-KG2/search?q=RTX%2Fcode%2Fkg2&type=code) where the phrase `RTX/code/kg2` appears; should now be `RTX-KG2`, I think
- [x] set up KG2 validation tests to run automatically in Travis CI

**Comment by saramsey** [comment]
For the Translator Prototypes Registry, I have logged the change as https://github.com/MaastrichtU-IDS/d2s-docs/pull/16

**Comment by ericawood** [comment]
Now that the checklist is complete, should we close this out?

**Comment by ericawood** [comment]
I'm going to close this issue out now that all the tasks are done.
