### ISSUE TITLE
KG2.6.3 has Non-Biolink Compliant Predicates

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX-KG2#55]
Reported by @chunyuma

- `biolink:has_count`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L687-L693 (node property slot)
- `biolink:has_quantitative_value`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L392-L405 (attribute slot)
- `biolink:has_route`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L999-L1009 (node property)
- `biolink:has_unit`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L418-L438 (attribute slot)
- `biolink:negatively_regulates`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L2390-L2411 (mixin)
- `biolink:positively_regulates`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L2366-L2383 (mixin)
- `biolink:quantifier_qualifier`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L4696-L4707 (association slot)
- `biolink:regulates`: https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L2335-L2358 (mixin)

@saramsey @kvarforl Thoughts on remapping these?

**Comment by saramsey** [comment]
ok, let's change `regulates` to `entity_regulates_entity`

**Comment by saramsey** [comment]
let's change `positively_regulates` to `entity_positively_regulates_entity`

**Comment by saramsey** [comment]
let's change `negatively_regulates` to `entity_negatively_regulates_entity`

**Comment by saramsey** [comment]
let's change the others to `related_to` I suppose

**Comment by saramsey** [comment]
Thank you @chunyuma and @ericawood for pointing out these issues

**Comment by saramsey** [comment]
I think it would be good if the `validate_predicate_remap_yaml.py` script could catch cases where we are using a biolink class that is a "mixin".

**Comment by ericawood** [comment]
> I think it would be good if the validate_predicate_remap_yaml.py script could catch cases where we are using a biolink class that is a "mixin".

I can update that script to do so, good suggestion!

**Comment by ericawood** [comment]
The fix for this caused the following issue:
https://travis-ci.com/github/RTXteam/RTX-KG2/builds/227044297#L400

**Comment by ericawood** [comment]
> I think it would be good if the validate_predicate_remap_yaml.py script could catch cases where we are using a biolink class that is a "mixin".

Commits 2df3663 and e30ad3b do this (and also exclude other non-predicates). @saramsey, could you please sanity check them for me to ensure that only non-predicates are being excluded?

**Comment by ericawood** [comment]
On KG2.6.5, I ran the Cypher query
`match ()-[e]-() where e.predicate in ['biolink:has_count', 'biolink:has_quantitative_value', 'biolink:has_route', 'biolink:has_unit', 'biolink:negatively_regulates', 'biolink:positively_regulates', 'biolink:quantifier_qualifier', 'biolink:regulates'] return e.predicate, count(e)`. There were no results, so I am going to close out this issue. (Further, there were no instances of these predicates in the `kg2-simplified-report.json` for KG2.6.5.
