### ISSUE TITLE
Question about DrugBank prefixes -- New and Updated Edges in DrugBank

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#59]
From @ericawood:

> Do you have any thoughts on biolink mappings for these predicates:
> DRUGBANK:aggregation_inhibitor
> DRUGBANK:binding
> DRUGBANK:chelator
> DRUGBANK:degradation
> DRUGBANK:deoxidizer
> DRUGBANK:desensitize_the_target
> DRUGBANK:downregulator
> DRUGBANK:gene_replacement
> DRUGBANK:incorporation_into_and_destabilization
> DRUGBANK:inhibition_of_synthesis
> DRUGBANK:intercalation
> DRUGBANK:neutralizer
> DRUGBANK:nucleotide_exchange_blocker
> DRUGBANK:oxidizer
> DRUGBANK:stablization

**Comment by saramsey** [comment]
For `DRUGBANK:binding`, how about `biolink:physically_interacts_with`?

**Comment by saramsey** [comment]
For `DRUGBANK:downregulator`, how about `biolink:entity_negatively_regulates_entity`?

**Comment by saramsey** [comment]
For `DRUGBANK:aggregation_inhibitor`, how about `biolink:decreases_activity_of`?

**Comment by saramsey** [comment]
For `DRUGBANK:binding`, how about `biolink:physically_interacts_with`?

**Comment by saramsey** [comment]
For `DRUGBANK:chelator`, how about `biolink:affects`?

**Comment by saramsey** [comment]
For `DRUGBANK:degradation`, how about `biolink:affects_degradation_of`?

**Comment by saramsey** [comment]
For `DRUGBANK:deoxidizer`, how about `biolink:decreases_molecular_modification_of`?

**Comment by saramsey** [comment]
For `DRUGBANK:desensitize_the_target`, how about `biolink:decreases_response_to`?

**Comment by saramsey** [comment]
For `DRUGBANK:gene_replacement`, how about `biolink:close_match`?

**Comment by saramsey** [comment]
For `DRUGBANK:incorporation_into_and_destabilization`, how about `biolink:affects_degradation_of`?

**Comment by saramsey** [comment]
For `DRUGBANK:inhibition_of_synthesis`, how about `biolink:entity_negatively_regulates_entity`?

**Comment by saramsey** [comment]
For `DRUGBANK:intercalation`, how about `biolink:molecularly_interacts_with` ?

**Comment by saramsey** [comment]
I will work on the rest later. Am late to pick up the kids

**Comment by ericawood** [comment]
Ok, sounds good. Thank you!

**Comment by ericawood** [comment]
What about:
* `DRUGBANK:nucleotide_exchange_blocker` -> `biolink:decreases_activity_of`
* `DRUGBANK:oxidizer` -> `biolink:increases_molecular_modification_of`
* `DRUGBANK:stablization` -> `biolink:increases_stability_of`

I'm still not sure about `DRUGBANK:neutralizer`. I didn't see anything about neutralization in the biolink model.

**Comment by saramsey** [comment]
Looks good

**Comment by ericawood** [comment]
This is incorporated into KG2 as of KG2.7.1. I'm going to close this issue.
