### ISSUE TITLE
Null-valued `knowledge_graph` should be acceptable

### ISSUE THREAD

**Issue by patrickkwang** [RTXteam/RTX-KG2#73]
```bash
curl -X 'POST' \
  'https://arax.ncats.io/api/rtxkg2/v1.1/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"message": {"query_graph": {"nodes": {"n0": {"ids": ["UniProtKB:Q12791"], "categories": ["biolink:Gene"], "is_set": false, "constraints": null}, "n1": {"ids": null, "categories": ["biolink:Disease"], "is_set": false, "constraints": null}}, "edges": {"e0": {"subject": "n1", "object": "n0", "predicates": ["biolink:is_sequence_variant_of"], "relation": null, "constraints": null}}}, "knowledge_graph": null, "results": null}, "log_level": null}'
```
and we get the response:
```json
{
  "detail": "None is not of type 'object' - 'message.knowledge_graph'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```
`knowledge_graph` is nullable, so I think this is validating incorrectly.

**Comment by edeutsch** [comment]
I @patrickkwang you are correct that this is validating incorrectly.
Unfortunately it is not our code that is causing the validation error, but rather the framework we are using.
I tried adding some more nullable: true entries in the OpenAPI definition to no avail.
I can't seem to convince it that null is allowed here.
I don't see an easy answer. I will work on it some more later, it does not seem to be an easy fix.
I think you said that others had the same problem? It would be useful to see if anyone else who has the problem can figure out the fix.

**Comment by edeutsch** [comment]
Hi @patrickkwang I have found and implemented a fix for this. Let me know if you have further trouble. Please close if this works for you.

**Comment by patrickkwang** [comment]
Looks great, thanks!
