### ISSUE TITLE
Need to Update SemMedDB

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX-KG2#87]
We are currently using version 42:
https://github.com/RTXteam/RTX-KG2/blob/225404444cbce9443a5f047b76454ca7754a51b3/extract-semmeddb.sh#L25-L30

This version has been deprecated:
![image](https://user-images.githubusercontent.com/36611732/124169955-b0526100-da5b-11eb-87d3-7a26fbdd04e2.png)

So, we should update to version 43:
![image](https://user-images.githubusercontent.com/36611732/124170238-09ba9000-da5c-11eb-931f-b09564fa8bd3.png)

Here is the link to the download page: https://ii.nlm.nih.gov/SemRep_SemMedDB_SKR/SemMedDB/SemMedDB_download.shtml

**Comment by ericawood** [comment]
Since there will be a lot of changes with the Biolink 2.0 build (#64), we are going to include this updated version in the following build (`KG2.7.1`).

(Based on discussion with @edeutsch and @saramsey)

**Comment by saramsey** [comment]
SemMedDB version 43 is now being loaded in build KG2.7.2. See #104 for details.
