### ISSUE TITLE
represent inverted pairs in KG2 as "biolink:related_to"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#9]
Following up on a conversation with @kvarforl and @ericawood today: it would be helpful if we could detect inverse predicate relationships (like between `has part` and `part of`) in the Biolink metamodel and represent them as edges between the predicates' _nodes_ in KG2. I believe this can be done using `ontobio`. Let's suppose the predicate CURIE is `biolink:part_of`. We could find its inverted partner like so:
```
import ontobio
import pprint
ont = ontobio.ontol_factory.OntologyFactory().create("biolink-model.owl.json")
curie = 'biolink:part_of'
pprint.pprint([{n: next(iter(ont.child_parent_relations(n, curie)))} for n in list(ont.get_graph().neighbors(curie))])
```
this will print:
```
[{'biolink:has_part': 'inverseOf'},
 {'biolink:food_component_of': 'subPropertyOf'},
 {'biolink:is_active_ingredient_of': 'subPropertyOf'},
 {'biolink:is_excipient_of': 'subPropertyOf'}]
```
so it shows that `biolink:has_part` is the inverted friend for `biolink:part_of`. So we would create an edge with source relation `owl:inverseOf` with subject `biolink:part_of` and object `biolink:has_part`, and a second edge with the subject and object IDs swapped. Then, in `predicate-remap.yaml`, we would map source relation `owl:inverseOf` to `biolink:related_to`. Thank you!

**Comment by ericawood** [comment]
This appears to be solved in KG2.6.5, so I'm closing this issue:
![image](https://user-images.githubusercontent.com/36611732/122802034-be44fc80-d279-11eb-9d6b-0774d2fa59d3.png)
