### ISSUE TITLE
Arbitrary Cap on Number of Nodes From HMDB

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#94]
See line 638 below:

https://github.com/RTXteam/RTX-KG2/blob/48b949af1255da66ae7d6786a0bbcf83cbd24efc/hmdb_xml_to_kg_json.py#L633-L650

**Comment by ericawood** [comment]
These changes have been made in the issue95 branch, but they are largely finished, so I'm going to add the verify tag on this issue.

**Comment by ecwood** [comment]
This miniature report from `kg2-hmdb.json` from `KG2.8.3` confirms this has been fixed:
```
{
    "_number_of_nodes": 217921,
    "_number_of_edges": 1869706,
    "_report_datetime": "2023-06-21 19:47:16"
}
```
