### ISSUE TITLE
SNOMED nodes in KG2.7.1

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#98]
I noticed that there are about 9,000 nodes in KG2.7.1 that have an ID starting with `SNOMED:`

seems unexpected given that we started excluding SNOMED from KG2 with KG2.6.7, and I confirmed that KG2.6.7 doesn't have any nodes with `SNOMED:__` IDs. 

looks like they're basically all coming from MONDO:
```
match (n) where n.id starts with "SNOMED:" return n.knowledge_source, count(distinct n) order by count(distinct n) desc
```
n.knowledge_source | count(distinct n)
-- | --
"infores:mondo" | 9000
"infores:genepio" | 1

(@ericawood confirmed this seems unusual in Slack and said they'll look into it)

**Comment by saramsey** [comment]
Erica and I decided that the KG2 team will try to fix this issue in 2.7.2, and that we will not hold up roll-out of 2.7.1 over this issue. Is that OK?

**Comment by amykglen** [comment]
yep, sounds good to me!

**Comment by ecwood** [comment]
Surprisingly, this is still an issue, but a very minor one now. There is only one `SNOMED:` node left in KG2, as of `KG2.8.3`.

```
match (n) where n.id starts with "SNOMED:" return n.provided_by, count(distinct n) order by count(distinct n) desc
```

n.provided_by | count(distinct n)
-- | --
"['infores:genepio']" | 1

**Comment by saramsey** [comment]
Huh, KG2 never ceases to amaze me. I wonder how that got in there?

**Comment by saramsey** [comment]
It's still in KG2.8.6pre:
```
(venv) sramsey-laptop:automat-test sramsey$ python3 find_snomed.py | grep SNOMED
SNOMED:22642004
```

**Comment by saramsey** [comment]
Here is the node JSON for that node:
```
{
    "category": "biolink:NamedThing",
    "category_label": "named_thing",
    "creation_date": null,
    "deprecated": false,
    "description": "An assay for detecting bacteria by subjecting them to strain-specific bacteriophages.",
    "full_name": null,
    "has_biological_sequence": null,
    "id": "SNOMED:22642004",
    "iri": "http://www.snomedbrowser.com/Codes/Details/22642004",
    "name": "Bacterial bacteriophage typing",
    "provided_by": [
        "infores:genepio"
    ],
    "publications": [],
    "replaced_by": null,
    "synonym": [],
    "update_date": "2023-09-08 22:01:14 GMT"
}
```

**Comment by saramsey** [comment]
OK, I checked on `kg285build.rtx.ai`, and found  the following in `genepio.owl`:
```
    <!-- http://snomed.info/sct/22642004 -->

    <owl:Class rdf:about="http://snomed.info/sct/22642004">
        <rdfs:subClassOf rdf:resource="&obo;OBI_0000070"/>
        <obo:IAO_0000412 rdf:resource="http://snomed.info/sct/900000000000207008"/>
        <rdfs:label xml:lang="en">Bacterial bacteriophage typing</rdfs:label>
        <rdfs:seeAlso>http://phinvads.cdc.gov/vads/http:/phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&amp;code=22642004</rdfs:seeAlso>
    </owl:Class>
```
I can live with this. Closing this issue.

**Comment by ecwood** [comment]
If you delete the SNOMED mapping in the mapping YAML files, that might solve this issue. (Also, as a reminder, please rely on the umls.jsonl file in ~/kg2-build/ rather than the TTL files now, with the new UMLS ETL process @saramsey, it will be more up to date).

**Comment by saramsey** [comment]
Thank you @ecwood !
